# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import learning_platform_pb2 as learning__platform__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in learning_platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearningPlatformStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearCurso = channel.unary_unary(
                '/learning.LearningPlatform/CrearCurso',
                request_serializer=learning__platform__pb2.Curso.SerializeToString,
                response_deserializer=learning__platform__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ObtenerCurso = channel.unary_unary(
                '/learning.LearningPlatform/ObtenerCurso',
                request_serializer=learning__platform__pb2.ID.SerializeToString,
                response_deserializer=learning__platform__pb2.Curso.FromString,
                _registered_method=True)
        self.ActualizarCurso = channel.unary_unary(
                '/learning.LearningPlatform/ActualizarCurso',
                request_serializer=learning__platform__pb2.Curso.SerializeToString,
                response_deserializer=learning__platform__pb2.Respuesta.FromString,
                _registered_method=True)
        self.EliminarCurso = channel.unary_unary(
                '/learning.LearningPlatform/EliminarCurso',
                request_serializer=learning__platform__pb2.ID.SerializeToString,
                response_deserializer=learning__platform__pb2.Respuesta.FromString,
                _registered_method=True)
        self.CrearEstudiante = channel.unary_unary(
                '/learning.LearningPlatform/CrearEstudiante',
                request_serializer=learning__platform__pb2.Estudiante.SerializeToString,
                response_deserializer=learning__platform__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ObtenerEstudiante = channel.unary_unary(
                '/learning.LearningPlatform/ObtenerEstudiante',
                request_serializer=learning__platform__pb2.ID.SerializeToString,
                response_deserializer=learning__platform__pb2.Estudiante.FromString,
                _registered_method=True)
        self.ActualizarEstudiante = channel.unary_unary(
                '/learning.LearningPlatform/ActualizarEstudiante',
                request_serializer=learning__platform__pb2.Estudiante.SerializeToString,
                response_deserializer=learning__platform__pb2.Respuesta.FromString,
                _registered_method=True)
        self.EliminarEstudiante = channel.unary_unary(
                '/learning.LearningPlatform/EliminarEstudiante',
                request_serializer=learning__platform__pb2.ID.SerializeToString,
                response_deserializer=learning__platform__pb2.Respuesta.FromString,
                _registered_method=True)


class LearningPlatformServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearCurso(self, request, context):
        """Servicios CRUD para Cursos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearEstudiante(self, request, context):
        """Servicios CRUD para Estudiantes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearningPlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearCurso,
                    request_deserializer=learning__platform__pb2.Curso.FromString,
                    response_serializer=learning__platform__pb2.Respuesta.SerializeToString,
            ),
            'ObtenerCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCurso,
                    request_deserializer=learning__platform__pb2.ID.FromString,
                    response_serializer=learning__platform__pb2.Curso.SerializeToString,
            ),
            'ActualizarCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarCurso,
                    request_deserializer=learning__platform__pb2.Curso.FromString,
                    response_serializer=learning__platform__pb2.Respuesta.SerializeToString,
            ),
            'EliminarCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarCurso,
                    request_deserializer=learning__platform__pb2.ID.FromString,
                    response_serializer=learning__platform__pb2.Respuesta.SerializeToString,
            ),
            'CrearEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearEstudiante,
                    request_deserializer=learning__platform__pb2.Estudiante.FromString,
                    response_serializer=learning__platform__pb2.Respuesta.SerializeToString,
            ),
            'ObtenerEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstudiante,
                    request_deserializer=learning__platform__pb2.ID.FromString,
                    response_serializer=learning__platform__pb2.Estudiante.SerializeToString,
            ),
            'ActualizarEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarEstudiante,
                    request_deserializer=learning__platform__pb2.Estudiante.FromString,
                    response_serializer=learning__platform__pb2.Respuesta.SerializeToString,
            ),
            'EliminarEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarEstudiante,
                    request_deserializer=learning__platform__pb2.ID.FromString,
                    response_serializer=learning__platform__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'learning.LearningPlatform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('learning.LearningPlatform', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearningPlatform(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/CrearCurso',
            learning__platform__pb2.Curso.SerializeToString,
            learning__platform__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/ObtenerCurso',
            learning__platform__pb2.ID.SerializeToString,
            learning__platform__pb2.Curso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/ActualizarCurso',
            learning__platform__pb2.Curso.SerializeToString,
            learning__platform__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/EliminarCurso',
            learning__platform__pb2.ID.SerializeToString,
            learning__platform__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/CrearEstudiante',
            learning__platform__pb2.Estudiante.SerializeToString,
            learning__platform__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/ObtenerEstudiante',
            learning__platform__pb2.ID.SerializeToString,
            learning__platform__pb2.Estudiante.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/ActualizarEstudiante',
            learning__platform__pb2.Estudiante.SerializeToString,
            learning__platform__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/learning.LearningPlatform/EliminarEstudiante',
            learning__platform__pb2.ID.SerializeToString,
            learning__platform__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
