# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: learning_platform.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'learning_platform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17learning_platform.proto\x12\x08learning\"a\n\x05\x43urso\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x14\n\x0c\x66\x65\x63ha_inicio\x18\x04 \x01(\t\x12\x11\n\tfecha_fin\x18\x05 \x01(\t\"R\n\nEstudiante\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x03 \x01(\t\x12\x18\n\x10\x63ursos_inscritos\x18\x04 \x03(\x05\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\tRespuesta\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd5\x03\n\x10LearningPlatform\x12\x32\n\nCrearCurso\x12\x0f.learning.Curso\x1a\x13.learning.Respuesta\x12-\n\x0cObtenerCurso\x12\x0c.learning.ID\x1a\x0f.learning.Curso\x12\x37\n\x0f\x41\x63tualizarCurso\x12\x0f.learning.Curso\x1a\x13.learning.Respuesta\x12\x32\n\rEliminarCurso\x12\x0c.learning.ID\x1a\x13.learning.Respuesta\x12<\n\x0f\x43rearEstudiante\x12\x14.learning.Estudiante\x1a\x13.learning.Respuesta\x12\x37\n\x11ObtenerEstudiante\x12\x0c.learning.ID\x1a\x14.learning.Estudiante\x12\x41\n\x14\x41\x63tualizarEstudiante\x12\x14.learning.Estudiante\x1a\x13.learning.Respuesta\x12\x37\n\x12\x45liminarEstudiante\x12\x0c.learning.ID\x1a\x13.learning.Respuestab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'learning_platform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURSO']._serialized_start=37
  _globals['_CURSO']._serialized_end=134
  _globals['_ESTUDIANTE']._serialized_start=136
  _globals['_ESTUDIANTE']._serialized_end=218
  _globals['_ID']._serialized_start=220
  _globals['_ID']._serialized_end=236
  _globals['_RESPUESTA']._serialized_start=238
  _globals['_RESPUESTA']._serialized_end=283
  _globals['_LEARNINGPLATFORM']._serialized_start=286
  _globals['_LEARNINGPLATFORM']._serialized_end=755
# @@protoc_insertion_point(module_scope)
